GET http://localhost:5051/authors

###################

GET http://localhost:5051/authors/64aeedb4ff4953dceb54284e

##################

POST http://localhost:5051/register/authors HTTP/1.1
Content-Type: application/json

{
	"name": "Pino",
    "secondName": "Insegno",
    "email": "pino@premiataditta.it",
    "birthDate": "02/01/1980",
    "password":"LAGATTANERA"
}