GET http://localhost:6060/authors

###################

GET http://localhost:6060/authors/64aeedb4ff4953dceb54284e

##################

POST http://localhost:6060/authors HTTP/1.1
Content-Type: "application/json"

{
	"name": "Silvio",
    "secondName": "Berlusconi",
    "email": "12344444@arcore.org",
    "dateBirth": "02/01/1902",
    "avatar": "http://budafdf.jpg"
}